project:
  type: website

website:
  title: "Sherry's IS415 Journey"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "In-Class Exercises"
        menu:
        - text: "In-Class Exercise 2"
          href: inclass_ex/inclass_ex02/In-class_Ex02.qmd
        - text: "In-Class Exercise 3"
          href: inclass_ex/inclass_ex03/inclass_ex03.qmd
          
      - text: "Hands-On Exercises"
        menu:
        - text: "Hands-On Exercise 2"
          href: handson_ex/handson_ex02/handson_ex02.qmd
        - text: "Hands-On Exercise 3"
          href: handson_ex/handson_ex03/handson_ex03.qmd
        - text: "Hands-On Exercise 4 (NEW!)"
          href: handson_ex/handson_ex04/handson_ex04.qmd
          
      - text: "Take-Home Exercises"
        menu:
        - text: "Take-Home Exercise 1"
          href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
        - text: "Take-Home Exercise 2"
          href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd
        - text: "Take-Home Exercise 3"
          href: Take-home_Ex/Take-home_Ex03/Take-home_Ex03.qmd
        
format:
  html:
    theme: lux
    css: styles.css

editor: visual
